### ISSUE TITLE
התייעצות: המרת כותרת ל-imdb id

### ISSUE THREAD

**Issue by burekas7** [wizupdate/service.subtitles.wizdom#1]
היי,

בעבר נעזרתי בפונקציה מההרחבה שלך שהחזירה
imdb id 
לפי כותרת בעזרת שאילתה לאתר שלך:
זה התבסס על הפונקציה הזו:

```
def getIMDBnumberByTVShowTitle_WithWizdom(title):
    domain = get_wizdom_domain()   
    imdb_id = urlopen("http://api.wizdom."+domain+"/search.tv.php?name="+quote(title)).read()
    return imdb_id
```

הבנתי שזה כבר לא קיים בדרך הזו. 
ולכן רציתי לדעת אם יש אופציה חדשה לאותה פעולה ואם כן אשמח לדעת איך. 
תודה מראש.

**Comment by wizupdate** [comment]
היי
אין כרגע אפשרות לחיפוש IMDB.
ההרחבה שלנו מסתמכת על ה-IMDB שהרחבות הוידאו מחזירות.
לאיזו הרחבה השתמשת באפשרות הזו?
מדוע אתה לא מסתמך על הנתונים שהרחבות הוידאו מחזירות?

**Comment by burekas7** [comment]
זה נועד עבור בדיקת כתוביות אופליין בהרחבת כתוביות אחרת.
נכון, ברוב הרחבות הוידאו המתוחזקות היום זה עובד תקין.
יש לי מקרה מסוים ספציפי שהאמת שאצלך זה דווקא עובד איכשהו אז צריך לחפור,
אבל בהרחבה אחרת זה לא.

המצב הוא כזה: בדיקה בספריית קודי - כתוביות עבור פרק, כאשר שמות הסדרות הן בעברית לפי בחירה בהגדרות של 
TVDB.
כאשר עומדים על פרק ורוצים לקבל את שם הסדרה מקבלים את השם בעברית, 
וכשמנסים להגיע לשם המקורי לפי 
json
הוא מחזיר סטרינג ריק, משום מה הסקרפר לא עושה את זה (שלחתי להם שאלה על זה לא התיחסו עדיין)
OriginalTitle
עובד רק לגבי סרטים ממה שהבנתי.

בנוסף, כשעומדים על הפרק ובודקים
IMDB
הוא מחזיר
ID 
אבל של הפרק כפי שנמצא ב-
TVDB
כי זה הסקרפר שלי

DBID
מחזיר ערך בבסיס נתונים בקודי וזה לא עוזר.

אז מנסה להבין איך מהנתונים הקיימים:
איך אני ממיר שם סדרה בעברית לאנגלית בשביל החיפוש באותו אתר.
או איך אני ממיר
ID
של פרק ב-
TVDB
לשם הסדרה באנגלית.

האמת שהנושא כאן לא רלוונטי, כי בעבר הפונקציה הזו הייתה שלב שני בתהליך אחרי שהוצאתי את שם הסדרה המקורי באנגלית ואז בעזרתך המרתי ל-
imdb
ואז השלב הבא היה להמיר את
imdb
ל-
tvdb
ומשם מחלץ את השם באנגלית.
חח מסורבל אבל עבד.
אז הבעיה שלי כרגע להמיר שם בעברית לשם באנגלית כי קודי מחזיר שם מקורי ריק.

**Comment by burekas7** [comment]
ראיתי שעכשיו אתה עובר דרך
TMDB
בכל אופן אני מנסה לממש משהו דומה, יש לי בעיה בפייתון
אתה משתמש במודול
requests
בשביל להשתמש ב-
get
`from requests import get`
אבל למה אצלי כשההרחבה רצה אז הוא לא מצליח לזהות את המודול ואצלך כן?

**Comment by burekas7** [comment]
הסתדרתי בסוף תודה
